### ISSUE TITLE
Neues Google+, der "+1 Entferner" funzt nicht mehr

### ISSUE THREAD

**Issue by OptimizerBug** [Guacam-Ole/GooglePlusOptimizer#37]
Reporter: <br/>Servus.
Seit dem Relaunch von Google+ im neuen Design bekomme ich trotz aktivem Filter wieder die +1 Empfehlungen meiner Kreislinge in den Stream.

**Comment by Guacam-Ole** [comment]
Im neuen Layout funktioniert derzeit der Optimizer gar nicht. Ich bin aber bereits dabei, dass zu beheben. Kann aber noch ein paar Tage dauern

**Comment by Guacam-Ole** [comment]
Ok. Das "Ein paar Tage" war zu optimistisch. :) Komm da derzeit leider nicht zu.

**Comment by Guacam-Ole** [comment]
fixed
