### ISSUE TITLE
Neues Google+: "Angesagte Sammlungen" werden nicht entfernt

### ISSUE THREAD

**Issue by OptimizerBug** [Guacam-Ole/GooglePlusOptimizer#39]
Trotz aktiviertem Filter erscheinen im Stream diese unerwünschten "Tipps".

**Comment by Guacam-Ole** [comment]
Das neue Layout haut noch nicht so wirklich hin. Das wird auch noch etwas dauern.

**Comment by Guacam-Ole** [comment]
Sollte mit 5.x jetzt gehen
